# Generated by Django 2.2.12 on 2023-08-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('lecturer', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('audience', models.IntegerField()),
            ],
        ),
    ]
